<a href="https://colab.research.google.com/github/MPRASHANTB/PRASHANT/blob/main/OJT_AssignmentQ3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Q3 Singular Value Decomposition (SVD):

import numpy as np

# Set the random seed
np.random.seed(27)

# Create a 5x5 matrix with random integers between 0 and 9
A = np.random.randint(0, 10, size=(5, 5))

print("Original Matrix A:")
print(A)

# Perform Singular Value Decomposition
U, Sigma, Vt = np.linalg.svd(A)

# Construct Sigma matrix (convert to diagonal matrix)
Sigma_matrix = np.diag(Sigma)

# Verify that A equals the product of U, Sigma, and Vt
A_reconstructed = np.dot(U, np.dot(Sigma_matrix, Vt))
print("\nIs A equals to U * Sigma * Vt: ", np.allclose(A, A_reconstructed))

# Print U, Sigma, and Vt matrices
print("\nMatrix U:")
print(U)
print("\nMatrix Sigma:")
print(Sigma_matrix)
print("\nMatrix Vt:")
print(Vt)

# Rank 2 approximation of matrix A
rank_2_approximation = np.dot(U[:, :2], np.dot(np.diag(Sigma[:2]), Vt[:2, :]))
print("\nRank 2 Approximation of Matrix A:")
print(rank_2_approximation)

# Rank 3 approximation of matrix A
rank_3_approximation = np.dot(U[:, :3], np.dot(np.diag(Sigma[:3]), Vt[:3, :]))
print("\nRank 3 Approximation of Matrix A:")
print(rank_3_approximation)

Original Matrix A:
[[3 8 8 8 0]
 [5 8 9 1 2]
 [1 1 4 6 3]
 [3 0 5 3 3]
 [6 7 2 7 8]]

Is A equals to U * Sigma * Vt:  True

Matrix U:
[[-0.56509287  0.33554337 -0.47580853 -0.49685988 -0.30792404]
 [-0.50173996  0.55518042  0.53357846  0.24165433  0.3113341 ]
 [-0.28472728 -0.23143435 -0.55464206  0.26625614  0.69774521]
 [-0.25464358 -0.07276184 -0.18068993  0.76211057 -0.56249532]
 [-0.53199069 -0.72133848  0.38551732 -0.20743336 -0.07074249]]

Matrix Sigma:
[[23.62982479  0.          0.          0.          0.        ]
 [ 0.          8.46263633  0.          0.          0.        ]
 [ 0.          0.          6.18060067  0.          0.        ]
 [ 0.          0.          0.          4.88726698  0.        ]
 [ 0.          0.          0.          0.          0.96434626]]

Matrix Vt:
[[-0.35736958 -0.53082597 -0.52952195 -0.47476916 -0.29105243]
 [-0.11760148  0.21801558  0.58477607 -0.40374341 -0.65853421]
 [ 0.39751133  0.4216643  -0.21927405 -0.71905482  0.31474279]
 [ 0.20986775 -0.6