<a href="https://colab.research.google.com/github/MPRASHANTB/PRASHANT/blob/main/OJT_AssignmentQ2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Q2 Row Echelon Form:
import numpy as np

# Set the random seed
np.random.seed(27)

# Create a 5x5 matrix with random integers between 0 and 9
A = np.random.randint(0, 10, size=(5, 5))

print("Original Matrix A:")
print(A)

# Function to perform elementary row operations to reduce matrix to Row Echelon Form
def row_echelon_form(matrix):
    m, n = matrix.shape
    lead = 0
    for r in range(m):
        if lead >= n:
            break
        i = r
        while matrix[i, lead] == 0:
            i += 1
            if i == m:
                i = r
                lead += 1
                if n == lead:
                    return matrix
        matrix[[i, r]] = matrix[[r, i]]
        lv = matrix[r, lead]
        matrix[r] = matrix[r] / lv
        for i in range(m):
            if i != r:
                lv = matrix[i, lead]
                matrix[i] -= lv * matrix[r]
        lead += 1
    return matrix

# Reduce matrix A to its Row Echelon Form
row_echelon_A = row_echelon_form(A.copy())

print("\nRow Echelon Form of Matrix A:")
print(row_echelon_A)

Original Matrix A:
[[3 8 8 8 0]
 [5 8 9 1 2]
 [1 1 4 6 3]
 [3 0 5 3 3]
 [6 7 2 7 8]]

Row Echelon Form of Matrix A:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
